app_name: cit
license_plate: b4e935
replicas: 1
image_stream_tag: prod
namespace_env: prod
limits_cpu: 250m
limits_memory: 512Mi
requests_cpu: 150m
requests_memory: 512Mi
docker_host: image-registry.openshift-image-registry.svc:5000
#stateful_requests_cpu: 50m
#stateful_requests_memory: 50Mi
#stateful_limit_cpu: 500m
#stateful_limit_memory: 500Mi
#volume_size: 200Mi
#replication_password: testing123
#root_password: testing456