app_name: cit
license_plate: b4e935
replicas: 1
image_stream_tag: develop
namespace_env: dev
limits_cpu: 250m
limits_memory: 512Mi
requests_cpu: 150m
requests_memory: 512Mi
docker_host: image-registry.openshift-image-registry.svc:5000
cluster: silver
stateful_requests_cpu: 50m
stateful_requests_memory: 50Mi
stateful_limit_cpu: 200m
stateful_limit_memory: 250Mi
volume_size: 200Mi
replication_password: testing123
root_password: testing456