# This workflow will build and push a new backend container image to Azure ACR and the Openshift Image Stream Tools
name: Backend Build and Push (Test)

on:
  push:
    branches: [openshift]
    #paths:
    #  - 'cit-api/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
      
      - name: "Build backend"
        run: |
          docker build cit-api -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/cit-webapi:latest -t image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/cit-webapi:develop
          docker images
      
      #- name: "Push backend to Azure"
      #  uses: azure/docker-login@v1
      #  with:
      #    login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #    username: ${{ secrets.REGISTRY_USERNAME }}
      #    password: ${{ secrets.REGISTRY_PASSWORD }}
      #- run: |
      #    docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/cit-webapi:latest
      
      - name: "Push backend to Openshift" 
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: serviceaccount
          password: ${{ secrets.OCP_REGISTRY_PASSWORD }}
      - run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/cit-webapi:develop
      
      - name: Vulnerability Scan Backend
        uses: Azure/container-scan@v0
        continue-on-error: true
        with:
          image-name: ${{ secrets.REGISTRY_LOGIN_SERVER }}/cit-webapi:latest
     